package jlu.edu.cn.lsh.po;

import java.math.BigDecimal;

public class Cartitem {

    private String cartitemid;

    private Integer quantity;

    private String bid;

    private String uid;

    private Integer orderby;

    /*public static void main(String[] args){
        BigDecimal b1 = new BigDecimal(2.0+"");
        BigDecimal b2 = new BigDecimal(1.1+"");
        BigDecimal b3 = b1.subtract(b2);
        //BigDecimal bigDecimal = new BigDecimal((2.0-1.1));
        System.out.println(b3.doubleValue());
    }*/

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.cartItemId
     *
     * @return the value of cartitem.cartItemId
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public String getCartitemid() {
        return cartitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.cartItemId
     *
     * @param cartitemid the value for cartitem.cartItemId
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public void setCartitemid(String cartitemid) {
        this.cartitemid = cartitemid == null ? null : cartitemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.quantity
     *
     * @return the value of cartitem.quantity
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.quantity
     *
     * @param quantity the value for cartitem.quantity
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.bid
     *
     * @return the value of cartitem.bid
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public String getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.bid
     *
     * @param bid the value for cartitem.bid
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public void setBid(String bid) {
        this.bid = bid == null ? null : bid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.uid
     *
     * @return the value of cartitem.uid
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.uid
     *
     * @param uid the value for cartitem.uid
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.orderBy
     *
     * @return the value of cartitem.orderBy
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public Integer getOrderby() {
        return orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.orderBy
     *
     * @param orderby the value for cartitem.orderBy
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }
}