package jlu.edu.cn.lsh.po;

import java.math.BigDecimal;

public class Order {

    private String oid;

    private String ordertime;

    private BigDecimal total;

    private Integer status;
    //1.未付款2.付款未发货3.发货未确认收货4.确认收货交易成功5.已取消（只能在未付款状态才可以）
    //1-5,1-2-3-4

    private String address;

    private String uid;

    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.oid
     *
     * @param oid the value for order.oid
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ordertime
     *
     * @return the value of order.ordertime
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public String getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ordertime
     *
     * @param ordertime the value for order.ordertime
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public void setOrdertime(String ordertime) {
        this.ordertime = ordertime == null ? null : ordertime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total
     *
     * @return the value of order.total
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total
     *
     * @param total the value for order.total
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.address
     *
     * @return the value of order.address
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.address
     *
     * @param address the value for order.address
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.uid
     *
     * @return the value of order.uid
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.uid
     *
     * @param uid the value for order.uid
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }
}