package jlu.edu.cn.lsh.po;

import java.math.BigDecimal;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bid
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private String bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bname
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private String bname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.price
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.currprice
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private BigDecimal currprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.discount
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.press
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private String press;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publishtime
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private String publishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.edition
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private Integer edition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.pagenum
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private Integer pagenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.wordnum
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private Integer wordnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.printtime
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private String printtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.booksize
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private Integer booksize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.paper
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private String paper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.cid
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.imageW
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private String imagew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.imageB
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private String imageb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.orderby
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private Integer orderby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bid
     *
     * @return the value of book.bid
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public String getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bid
     *
     * @param bid the value for book.bid
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setBid(String bid) {
        this.bid = bid == null ? null : bid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bname
     *
     * @return the value of book.bname
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bname
     *
     * @param bname the value for book.bname
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setBname(String bname) {
        this.bname = bname == null ? null : bname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author
     *
     * @return the value of book.author
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author
     *
     * @param author the value for book.author
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.price
     *
     * @return the value of book.price
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.price
     *
     * @param price the value for book.price
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.currprice
     *
     * @return the value of book.currprice
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public BigDecimal getCurrprice() {
        return currprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.currprice
     *
     * @param currprice the value for book.currprice
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setCurrprice(BigDecimal currprice) {
        this.currprice = currprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.discount
     *
     * @return the value of book.discount
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.discount
     *
     * @param discount the value for book.discount
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.press
     *
     * @return the value of book.press
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public String getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.press
     *
     * @param press the value for book.press
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setPress(String press) {
        this.press = press == null ? null : press.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publishtime
     *
     * @return the value of book.publishtime
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public String getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publishtime
     *
     * @param publishtime the value for book.publishtime
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setPublishtime(String publishtime) {
        this.publishtime = publishtime == null ? null : publishtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.edition
     *
     * @return the value of book.edition
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public Integer getEdition() {
        return edition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.edition
     *
     * @param edition the value for book.edition
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setEdition(Integer edition) {
        this.edition = edition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.pagenum
     *
     * @return the value of book.pagenum
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public Integer getPagenum() {
        return pagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.pagenum
     *
     * @param pagenum the value for book.pagenum
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setPagenum(Integer pagenum) {
        this.pagenum = pagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.wordnum
     *
     * @return the value of book.wordnum
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public Integer getWordnum() {
        return wordnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.wordnum
     *
     * @param wordnum the value for book.wordnum
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setWordnum(Integer wordnum) {
        this.wordnum = wordnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.printtime
     *
     * @return the value of book.printtime
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public String getPrinttime() {
        return printtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.printtime
     *
     * @param printtime the value for book.printtime
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setPrinttime(String printtime) {
        this.printtime = printtime == null ? null : printtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.booksize
     *
     * @return the value of book.booksize
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public Integer getBooksize() {
        return booksize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.booksize
     *
     * @param booksize the value for book.booksize
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setBooksize(Integer booksize) {
        this.booksize = booksize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.paper
     *
     * @return the value of book.paper
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public String getPaper() {
        return paper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.paper
     *
     * @param paper the value for book.paper
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setPaper(String paper) {
        this.paper = paper == null ? null : paper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.cid
     *
     * @return the value of book.cid
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.cid
     *
     * @param cid the value for book.cid
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.imageW
     *
     * @return the value of book.imageW
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public String getImagew() {
        return imagew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.imageW
     *
     * @param imagew the value for book.imageW
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setImagew(String imagew) {
        this.imagew = imagew == null ? null : imagew.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.imageB
     *
     * @return the value of book.imageB
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public String getImageb() {
        return imageb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.imageB
     *
     * @param imageb the value for book.imageB
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setImageb(String imageb) {
        this.imageb = imageb == null ? null : imageb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.orderby
     *
     * @return the value of book.orderby
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public Integer getOrderby() {
        return orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.orderby
     *
     * @param orderby the value for book.orderby
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }
}