package jlu.edu.cn.lsh.po;

import java.math.BigDecimal;

public class Orderitem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.orderItemId
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private String orderitemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.quantity
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.subtotal
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private BigDecimal subtotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.bid
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private String bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.bname
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private String bname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.currPrice
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private BigDecimal currprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.imageb
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private String imageb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.oid
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    private String oid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.orderItemId
     *
     * @return the value of orderitem.orderItemId
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public String getOrderitemid() {
        return orderitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.orderItemId
     *
     * @param orderitemid the value for orderitem.orderItemId
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setOrderitemid(String orderitemid) {
        this.orderitemid = orderitemid == null ? null : orderitemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.quantity
     *
     * @return the value of orderitem.quantity
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.quantity
     *
     * @param quantity the value for orderitem.quantity
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.subtotal
     *
     * @return the value of orderitem.subtotal
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public BigDecimal getSubtotal() {
        return subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.subtotal
     *
     * @param subtotal the value for orderitem.subtotal
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.bid
     *
     * @return the value of orderitem.bid
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public String getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.bid
     *
     * @param bid the value for orderitem.bid
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setBid(String bid) {
        this.bid = bid == null ? null : bid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.bname
     *
     * @return the value of orderitem.bname
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.bname
     *
     * @param bname the value for orderitem.bname
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setBname(String bname) {
        this.bname = bname == null ? null : bname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.currPrice
     *
     * @return the value of orderitem.currPrice
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public BigDecimal getCurrprice() {
        return currprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.currPrice
     *
     * @param currprice the value for orderitem.currPrice
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setCurrprice(BigDecimal currprice) {
        this.currprice = currprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.imageb
     *
     * @return the value of orderitem.imageb
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public String getImageb() {
        return imageb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.imageb
     *
     * @param imageb the value for orderitem.imageb
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setImageb(String imageb) {
        this.imageb = imageb == null ? null : imageb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.oid
     *
     * @return the value of orderitem.oid
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.oid
     *
     * @param oid the value for orderitem.oid
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }
}