package jlu.edu.cn.lsh.mapper;

import java.util.List;
import jlu.edu.cn.lsh.po.Book;
import jlu.edu.cn.lsh.po.BookExample;
import org.apache.ibatis.annotations.Param;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int countByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int deleteByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int deleteByPrimaryKey(String bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int insertSelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    List<Book> selectByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    Book selectByPrimaryKey(String bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") Book record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int updateByExample(@Param("record") Book record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int updateByPrimaryKeySelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int updateByPrimaryKey(Book record);
}