package jlu.edu.cn.lsh.mapper;

import java.util.List;
import jlu.edu.cn.lsh.po.Cartitem;
import jlu.edu.cn.lsh.po.CartitemExample;
import org.apache.ibatis.annotations.Param;

public interface CartitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int countByExample(CartitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int deleteByExample(CartitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int deleteByPrimaryKey(String cartitemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int insert(Cartitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int insertSelective(Cartitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    List<Cartitem> selectByExample(CartitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    Cartitem selectByPrimaryKey(String cartitemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") Cartitem record, @Param("example") CartitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int updateByExample(@Param("record") Cartitem record, @Param("example") CartitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int updateByPrimaryKeySelective(Cartitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int updateByPrimaryKey(Cartitem record);
}