package jlu.edu.cn.lsh.mapper;

import java.util.List;
import jlu.edu.cn.lsh.po.Orderitem;
import jlu.edu.cn.lsh.po.OrderitemExample;
import org.apache.ibatis.annotations.Param;

public interface OrderitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int countByExample(OrderitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int deleteByExample(OrderitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int deleteByPrimaryKey(String orderitemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int insert(Orderitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int insertSelective(Orderitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    List<Orderitem> selectByExample(OrderitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    Orderitem selectByPrimaryKey(String orderitemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") Orderitem record, @Param("example") OrderitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int updateByExample(@Param("record") Orderitem record, @Param("example") OrderitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int updateByPrimaryKeySelective(Orderitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated Wed Oct 10 15:13:11 CST 2018
     */
    int updateByPrimaryKey(Orderitem record);
}