package jlu.edu.cn.lsh.mapper;

import java.util.List;
import jlu.edu.cn.lsh.po.Category;
import jlu.edu.cn.lsh.po.CategoryCustom;
import jlu.edu.cn.lsh.po.CategoryExample;
import org.apache.ibatis.annotations.Param;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    int countByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    int deleteByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    int deleteByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    List<Category> selectByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    Category selectByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    int updateByExample(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    int updateByPrimaryKey(Category record);

    List<CategoryCustom> findFistClass();
    List<CategoryCustom> findSecondClass(String cid);
    public void addFirstClass(CategoryCustom categoryCustom)throws Exception;
    public void addSecondClass(CategoryCustom categoryCustom)throws Exception;
    CategoryCustom findClassByCid(String cid)throws Exception;
    public void updateCategoryByCid(CategoryCustom categoryCustom)throws Exception;
    public void updateCategorySecondClassByCid(CategoryCustom categoryCustom)throws Exception;
    public Integer findChildCountByParentId(String cid)throws Exception;
    public void deleteByCid(String cid)throws Exception;
}