package jlu.edu.cn.lsh.mapper;

import java.util.List;

import jlu.edu.cn.lsh.po.*;
import org.apache.ibatis.annotations.Param;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    int countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    int deleteByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    Order selectByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Tue Aug 28 16:08:01 CST 2018
     */
    int updateByPrimaryKey(Order record);


    /*新加的*/
    /*   private int pc;//当前页码
    private int tp;//总页数
    private int tr;//总记录数
    private int ps;//每页记录数
    private String url;//第一次查询时的条件，地址*/
    List<OrderCustom> findOrderByUid(OrderVo orderVo);
    OrderCustom findOrderByOid(String oid);

    List<OrderCustom> findAll(OrderVo orderVo);
    Integer findAllOrderCount()throws Exception;
    List<OrderCustom> findOrderByStatus(OrderVo orderVo)throws Exception;
    Integer findCountByStatus(Integer status)throws Exception;

}